name: integrate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        TEST_PHP_ARGS : "--show-diff"

    steps:
      #https://github.com/actions/checkout
    - uses: actions/checkout@v2
    - name: autoconf
      run: phpize
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test

